### ISSUE TITLE
Neither versions work for me

### ISSUE THREAD

**Issue by JustSayBoot** [a1928370421/Bongobs-Cat-Plugin#1]
This is all I see when I try it ![image](https://user-images.githubusercontent.com/39899462/83961497-74dd6700-a848-11ea-904a-4893448a25eb.png)

<s>Im guessing it might be an issue with my GPU cause it's an AMD card?</s>

<s>It seems your normal live2d obs plugin works just fine so im not sure the issue</s>

Got it to work by having your live2D plugin source and the bongocat source added at the same time

**Comment by a1928370421** [comment]
Hi, I think the problem is pixels size doesn't match. Try to set RenderTargetWidth to 1280 in define.cpp when you don't want use plugin source.

**Comment by a1928370421** [comment]
> This is all I see when I try it ![image](https://user-images.githubusercontent.com/39899462/83961497-74dd6700-a848-11ea-904a-4893448a25eb.png)
> 
> Im guessing it might be an issue with my GPU cause it's an AMD card?
> 
> It seems your normal live2d obs plugin works just fine so im not sure the issue
> 
> Got it to work by having your live2D plugin source and the bongocat source added at the same time
Hi, I think the problem is pixels size doesn't match. Try to set RenderTargetWidth to 1280 in define.cpp when you don't want use plugin source.

**Comment by JustSayBoot** [comment]
> Hi, I think the problem is pixels size doesn't match. Try to set RenderTargetWidth to 1280 in define.cpp when you don't want use plugin source.

Sorry I don't know how to compile it

**Comment by a1928370421** [comment]
> Sorry I don't know how to compile it
If you want to compile it as a OBS plugin ( .dll ) and test it in OBS.  Try to compile source with OBS-Studio source code.

**Comment by JustSayBoot** [comment]
> 
> 
> > Sorry I don't know how to compile it
> 
> If you want to compile it as a OBS plugin ( .dll ) and test it in OBS. Try to compile source with OBS-Studio source code.

Yeah I don't know anything about C++ or CMake etc etc so I won't worry about it
