### ISSUE TITLE
[Tip] you can change key mapping (customization)

### ISSUE THREAD

**Issue by roeniss** [a1928370421/Bongobs-Cat-Plugin#17]
1. Find the 'mania' config file. For me, it's here: `C:\Program Files\obs-studio\bin\64bit\Bango Cat\mode\mania\config.json`. (of course, you need to install first)
2. Open it with any editor as Administrator (you need root permission to edit it).
3. Change the values in `KeyUse` field. For me, I edited like this:
```js
{
// ...
  "KeyUse": [
    "d",
    "space",
    "k",
    ">"
  ],
// ...
}
```
(in this case, 'd' is the leftmost key in the image)
4. Restart obs, then re-import BongoCat plugin.

---

the reason that I change only the 'mania' option is that this is the only case where each key name is not printed on image. If you don't mind, you can edit other configs like this.

By the way, @a1928370421, this is a pretty good plugins. I can add this guide to Readme if you want to! 😉 (or you can pin this issue)

**Comment by sukrosono** [comment]
yeah, he is too busy right now, well perhaps.
I think we also need some `development.md` for those who want to make code changes 😀

**Comment by Xlds27X** [comment]
do you know the KeyUse for escape?

**Comment by roeniss** [comment]
@Xlds27X no I didnt try that.

**Comment by rhombus9** [comment]
I couldn't find the way to add a key to 'KeyUse', but here are the available keys:
https://github.com/a1928370421/Bongobs-Cat-Plugin/blob/6075d8fe0c9a7b73a2d5d7155bb7b9c8b39cd6fe/Define.cpp#L47-L53
